site_name: TrustLLM
site_description: Trustworthiness in Large Language Models
use_directory_urls: false
extra_css:
  - stylesheets/extra.css
copyright: Copyright &copy; 2024 TrustLLM

nav:
  - Home: index.md
  - Guide:
    - Generation: guides/generation_details.md
    - Evaluation: guides/evaluation.md
  - Changelog: changelog.md
  - FAQ: faq.md

theme:
  custom_dir: images/
  name: material
  icon:
    logo: img.png
  font:
    text: Ubuntu
    code: Ubuntu Mono
  favicon: img.png
  logo: img.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - navigation.top
    - navigation.tracking
    - toc.follow
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: black
      primary: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/weather-night
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js